#!/bin/bash
#
# calc_censor input headrad fd dv mode
#
# input:   input prefix
# headrad: head radius (mm), default 50 [float]
# fd:      framewise displacement threshold (mm/TR), default 0.5 [float]
# dv:      DVARS threshold (%/TR), defaults 5 [float]
#
# output:
# others: retained_TRs censor
# prereq: motion_deskull calc_dvars
#
# This identifies motion-corrupted TRs from fMRI scans and outputs a .1D binary vector indicating good (1) and bad (0) TRs.

echo '*** MODULE: calc_censor. Flags TRs corrupted by motion.******************'
export input=${1}
export headrad=${2}
export fd=${3}
export dv=${4}

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        if [ ! -f ${SESS}/func_scrubbed.${ID}.${NUM}.nii.gz ]; then
            epi-censor \
                ${SESS}/${input}.${ID}.${NUM}.nii.gz \
                ${SESS}/PARAMS/censor.${ID}.${NUM}.1D \
                ${SESS}/PARAMS/motion.${ID}.${NUM}.1D \
                --DVARS ${SESS}/PARAMS/DVARS.${ID}.${NUM}.1D \
                --report ${SESS}/PARAMS/retained_TRs.${ID}.${NUM}.1D \
                --head ${headrad} \
                --FD ${fd} \
                --DV ${dv}
        fi
    done
done
