#!/bin/bash
#
# calc_gcor input
#
# input: input prefix
#
# output:
# prereq: motion_deskull
#
#  Calls an AFNI script to calculate the global correlation for each concatenated set of runs (across all sessions). Useful for resting state functional connectivity experiments.

echo '*** MODULE: calc_gcor. calculates global correlation in native space. **'
export input=${1}

## calculate global correlation for each run. NB: does not work on MNI data!!!
for SESS in $(ls -d ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/); do
    for FILE in $(ls ${SESS}/${input}.${ID}.*.nii.gz); do
        FNAME=`basename ${FILE}`
        if [ ! -f ${SESS}/${PARAMS}/${FNAME}.gcorr ]; then
            @compute_gcor \
                -input ${FILE} \
                -verb 0 \
                -mask ${SESS}/anat_EPI_mask.nii.gz \
                > ${SESS}/${PARAMS}/${FNAME}.gcorr
        fi
    done
done
