#!/bin/bash
#
# concatenate input
#
# input: input prefix
#
# output:
# others: func_concat
# prereq: init_*
#
# Concatenates all runs in order of a particular prefix with the current ID.

echo '*** MODULE: concatenate. Concatenates all functional runs. *************'
export input=${1}

# create concatenated runs in order
if [ ! -f ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/func_concat.nii.gz ]; then
    LIST=``
    DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
    for SESS in ${DIR_SESS}; do
        FILES=`ls ${SESS}/${input}.${ID}.*`
        LIST="${LIST} ${FILES}"
    done

    3dTcat \
        -prefix ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/func_concat.${ID}.nii.gz \
        $(echo ${LIST})
fi
