#!/bin/bash
#
# ica input mask
#
# input: input prefix
# mask:   epi brain mask [list: anat_EPI_mask anat_EPI_mask_MNI-lin anat_EPI_mask_MNI-nonlin anat_EPI_mask_T1 ?]
#
# output:
# prereq: init_* motion_deskull
#
# Runs ICA on each input functional file of the type defined using the default MELODIC settings. This module could be easily tweaked to grant the user access to the dimensionality estimation settings, if need be. The output is the full MELODIC report in a `.ica` folder.

echo '*** MODULE: ica. Runs MELODIC on each run. *****************************'
export input=${1}
export mask=${2}

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # run MELODIC, output some images of components (saves space)
        if [ ! -d ${SESS}/MELODIC.${ID}.${NUM}/ ]; then
            melodic \
                -i ${SESS}/${input}.${ID}.${NUM}.nii.gz \
                -o ${SESS}/MELODIC.${ID}.${NUM} \
                --mask=${SESS}/${mask}.nii.gz \
                --dimest=lap \
                --report \
                --Oall \
                --logPower
        fi
    done
done
