#!/bin/bash
#
# make_group_mni_mask
#
# output:
# others: anat_EPI_mask_MNI_group
# prereq: *linreg_epi2mni_*
#
# Creates a group-level MNI mask using all available MNI space EPI masks.

echo '*** MODULE: make_group_mni_mask. Makes a group-level MNI brain mask. ***'

# create group linear registration mask of the EPI data in MNI space
if [ -f ${DIR_DATA}/${DIR_EXPT}/anat_EPI_mask_MNI_group.nii.gz ]; then
    rm ${DIR_DATA}/${DIR_EXPT}/anat_EPI_mask_MNI_group.nii.gz
fi

# try finding nonlinear masks. if they exist, use those, otherwise use linear
inputs=$(find ${DIR_DATA}/${DIR_EXPT} -name anat_EPI_mask_MNI-nonlin.nii.gz)
nfiles=$(echo ${inputs} | wc -l)
if [ ! ${nfiles} -eq 0 ]; then
    mask=anat_EPI_mask_MNI-lin.nii.gz
else
    mask=anat_EPI_mask_MNI-nonlin.nii.gz
fi

# now collect the inputs, take the mean, and threshold at 0.999 (i.e., 100%)
inputs=$(find ${DIR_DATA}/${DIR_EXPT} -name ${mask})
3dMean \
    -datum short \
    -prefix ${DIR_DATA}/${DIR_EXPT}/tmp_mean.nii.gz \
    ${inputs}

3dcalc \
    -a ${DIR_DATA}/${DIR_EXPT}/tmp_mean.nii.gz \
    -expr 'step(a-0.999)' \
    -prefix ${DIR_DATA}/${DIR_EXPT}/anat_EPI_mask_MNI_group.nii.gz

rm ${DIR_DATA}/${DIR_EXPT}/tmp_mean.nii.gz

