#!/bin/bash
#
# slice_time_correct input tpattern
#
# input:    input prefix
# tpattern: slice timing at acquisition [list: alt+z alt+z2 alt-z alt-z2 seq+z seq-z]
#
# output: func_tshift
# prereq: init_*
#
# This performs slice time correction using the supplied slice timing pattern.

echo '*** MODULE: slice_time_correct. Corrects slice timing. ******************'
export input=${1}
export tpattern=${2}

# loop through sessions
DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do

    # loop through runs
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # slice time correction (can include specified timings)
        # NB: Physio regression must happen BEFORE NOW
        if [ ! -f ${SESS}/func_tshift.${ID}.${NUM}.nii.gz ]; then
            if [ -f ${RUN}/slice_timing.1D ]; then
                3dTshift \
                    -prefix ${SESS}/func_tshift.${ID}.${NUM}.nii.gz \
                    -verbose -Fourier \
                    -tpattern @ ${RUN}/slice_timing.1D \
                    ${SESS}/${input}.${ID}.${NUM}.nii.gz
            else
                3dTshift \
                    -prefix ${SESS}/func_tshift.${ID}.${NUM}.nii.gz \
                    -verbose -Fourier \
                    -tpattern ${tpattern} \
                    ${SESS}/${input}.${ID}.${NUM}.nii.gz
            fi
        fi
    done
done
