#!/bin/bash
#
# surfsmooth input fwhm
#
# input: input prefix
# fwhm:  full width half maximum of smoothing kernel [float]
#
# output: func_smooth
# prereq: vol2surf
#
# This spatially-smooths cortical data along the surface mesh, estimated by Freesurfer.

echo '*** MODULE: surfsmooth. Smooths functional data on a cortical surface **'
export input=${1}
export fwhm=${2}

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    SESS=`basename ${SESS}`        
    DIR=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/${SESS}`
    DIR_T1=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/T1/${SESS}`
    DIR_FS=`echo ${SUBJECTS_DIR}/${DIR_EXPT}_${SUB}_${SESS}`
    FS_NAME=`echo ${DIR_EXPT}_${SUB}_${SESS}`


    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`
        
        # smooth data on the cortical surface to fwhm
        if [ ! -f ${DIR}/func_smooth.L.${ID}.${NUM}.niml.dset ]; then
            SurfSmooth \
              -met HEAT_07 \
              -spec ${DIR_FS}/SUMA/${FS_NAME}_both.spec \
              -surf_A ${DIR_FS}/SUMA/lh.white.asc \
              -input ${DIR}/${input}.L.${ID}.${NUM}.niml.dset \
              -target_fwhm ${fwhm} \
              -output ${DIR}/func_smooth.L.${ID}.${NUM}.niml.dset
        fi

        if [ ! -f ${DIR}/func_smooth.R.${ID}.${NUM}.niml.dset ]; then
            SurfSmooth \
              -met HEAT_07 \
              -spec ${DIR_FS}/SUMA/${FS_NAME}_both.spec \
              -surf_A ${DIR_FS}/SUMA/rh.white.asc \
              -input ${DIR}/${input}.R.${ID}.${NUM}.niml.dset \
              -target_fwhm ${fwhm} \
              -output ${DIR}/func_smooth.R.${ID}.${NUM}.niml.dset
        fi
    done
done
