#!/bin/bash

cat <<"EOF"
echo '*** MODULE: t12mni_fsl_export. Copies T1 <--> MNI152 from HCP_DATA. ********'

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in `basename ${DIR_SESS}`; do

    DIR=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}`
    DIR_T1=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/T1`

    # If we have a T1 for each session, we register to the session T1.
    # Otherwise, we go to the first session.
    if [ `ls -l ${DIR} | grep ^d | wc -l` -eq \
         `ls -l ${DIR_T1} | grep ^d | wc -l` ]; then
        ANAT_T1=`echo ${DIR_T1}/${SESS}/anat_T1_brain.nii.gz`
        HCPSUBDIR="${HCP_DATA}/"${DIR_EXPT}_${SUB}_{SESS}/MNINonLinear/xfms/"
    else
        ANAT_T1=`echo ${DIR_T1}/SESS01/anat_T1_brain.nii.gz`
        HCPSUBDIR="${HCP_DATA}/"${DIR_EXPT}_${SUB}_SESS01/MNINonLinear/xfms"
    fi

    # copy registration of T1 to reg_T1_to_TAL
    if [ ! -f ${DIR}/${SESS}/mat_TAL_to_T1.mat ]; then
      cp ${HCPSUBDIR}/xfms/acpc2MNILinear.mat ${DIR}/${SESS}/mat_T1_to_TAL.mat
      cp ${HCPSUBDIR}/xfms/T1w_to_MNILinear.nii.gz  ${DIR}/${SESS}/reg_T1_to_TAL.nii.gz
      # invert flirt transform
      convert_xfm \
          -omat ${DIR}/${SESS}/mat_TAL_to_T1.mat \
          -inverse \
          ${DIR}/${SESS}/mat_T1_to_TAL.mat
    fi

    # copy non-linear registration  T1 to MNI
    if [ ! -f ${DIR}/${SESS}/reg_nlin_TAL_WARP.nii.gz ]; then
      cp ${HCPSUBDIR}/T1w.nii.gz ${DIR}/${SESS}/reg_nlin_TAL.nii.gz
      cp ${HCPSUBDIR}/xfms/acpc2standard_warp_noaffine.nii.gz ${DIR}/${SESS}/reg_nlin_TAL_WARP.nii.gz
    fi
done

EOF
