#!/bin/bash

cat <<EOF
INPUT=`echo 'func_'${1}`
POLORT=`echo ${2}`
GS_FLAG=`echo ${3}`
VENT_FLAG=`echo ${4}`
DV_FLAG=`echo ${5}`
WM_LOC_FLAG=`echo ${6}`
WM_GLO_FLAG=`echo ${7}`

echo '************************************************************************'
echo '                  Time series filtering of fMRI data'
echo ''
echo '   - Computes nusiance time series from tissues, motion paramaters,'
echo '   - Optionally uses the global mean: ${GS_FLAG},'
echo '   - Optionally uses the ventricles: ${VENT_FLAG},'
echo '   - Optionally uses the draining vessels: ${DV_FLAG},'
echo '   - Optionally uses the local white matter: ${WM_LOC_FLAG},'
echo '   - Optionally uses the mean white matter: ${WM_GLO_FLAG},'
echo '   - Detrends each with legrende polynomials up to order ${POLORT},'
echo '   - Computes fit of run with all nusiances via linear regression,'
echo '   - Computes temporal signal to noise ratio,'
echo '   - Subtracts noise model from each voxel, retaining the mean.'
echo ''
echo '************************************************************************'

EOF

cat <<"EOF"
cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # detrend physiological regressors, if they exist
        if [ -f ${SESS}/PARAMS/phys.${UID}.${NUM}.1D ] && \
           [ ! -f ${SESS}/PARAMS/det.phys.${UID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/phys.${UID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.phys.${UID}.${NUM}.1D
        fi

        # detrend motion regressors
        if [ ! -f ${SESS}/PARAMS/det.motion.${UID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/motion.${UID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.motion.${UID}.${NUM}.1D
        fi

        if [ ! -f ${SESS}/PARAMS/det.lag.motion.${UID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.motion.${UID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.motion.${UID}.${NUM}.1D
        fi
        
        # detrend ventricle regressors 
        if [ ! -f ${SESS}/PARAMS/det.vent.${UID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/vent.${UID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.vent.${UID}.${NUM}.1D
        fi
        
        if [ ! -f ${SESS}/PARAMS/det.lag.vent.${UID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.vent.${UID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.vent.${UID}.${NUM}.1D
        fi

        # detrend draining vessel regressors
        if [ ! -f ${SESS}/PARAMS/det.dv.${UID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/dv.${UID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.dv.${UID}.${NUM}.1D
        fi
        
        if [ ! -f ${SESS}/PARAMS/det.lag.dv.${UID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.dv.${UID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.dv.${UID}.${NUM}.1D
        fi
        
        # detrend local white matter regressors
        if [ ! -f ${SESS}/PARAMS/det.wm_local15.${UID}.${NUM}.nii.gz ]; then
            3dDetrend \
                -prefix ${SESS}/PARAMS/det.wm_local15.${UID}.${NUM}.nii.gz \
                -polort ${POLORT} \
                ${SESS}/PARAMS/wm_local15.${UID}.${NUM}.nii.gz
        fi

        if [ ! -f ${SESS}/PARAMS/det.lag.wm_local15.${UID}.${NUM}.nii.gz ]; then
            3dDetrend \
                -prefix ${SESS}/PARAMS/det.lag.wm_local15.${UID}.${NUM}.nii.gz \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.wm_local15.${UID}.${NUM}.nii.gz
        fi

        # detrend mean white matter regressors
        if [ ! -f ${SESS}/PARAMS/det.wm.${UID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/wm.${UID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.wm.${UID}.${NUM}.1D
        fi

        if [ ! -f ${SESS}/PARAMS/det.lag.wm.${UID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.wm.${UID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.wm.${UID}.${NUM}.1D
        fi

        # detrend global mean regressors
        if [ ! -f ${SESS}/PARAMS/det.global_mean.${UID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/global_mean.${UID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.global_mean.${UID}.${NUM}.1D
        fi
        
        # fit each run with all nuisance regressors
        if [ ! -f ${SESS}/func_noise.${UID}.${NUM}.nii.gz ]; then

            # start with the standard motion-parameter regressors
            CMD=`echo 3dTfitter \
                          -prefix ${SESS}/func_noise_betas.${UID}.${NUM}.nii.gz \
                          -fitts ${SESS}/func_noise.${UID}.${NUM}.nii.gz \
                          -polort ${POLORT} \
                          -RHS ${SESS}/${INPUT}.${UID}.${NUM}.nii.gz \
                          -LHS ${SESS}/PARAMS/det.motion.${UID}.${NUM}.1D \
                               ${SESS}/PARAMS/det.lag.motion.${UID}.${NUM}.1D `

            # optionally add the global mean
            if [ `echo ${GS_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.global_mean.${UID}.${NUM}.1D`
            fi

            # optionally add the ventricles 
            if [ `echo ${VENT_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.vent.${UID}.${NUM}.1D`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.vent.${UID}.${NUM}.1D`
            fi

            # optionally add the draining vessles
            if [ `echo ${DV_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.dv.${UID}.${NUM}.1D`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.dv.${UID}.${NUM}.1D`
            fi

            # optionally add the local white matter regressors
            if [ `echo ${WM_LOC_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.wm_local15.${UID}.${NUM}.nii.gz`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.wm_local15.${UID}.${NUM}.nii.gz`
            fi
            
            # optionally add the global white matter regressors
            if [ `echo ${WM_GLO_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.wm.${UID}.${NUM}.nii.gz`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.wm.${UID}.${NUM}.nii.gz`
            fi
            
            # and add the physio regressors if they exist
            if [ -f ${SESS}/PARAMS/det.phys.${UID}.${NUM}.1D ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.phys.${UID}.${NUM}.1D`
            fi

            ${CMD}

        fi

        # compute mean, standard deviation
        if [ ! -f ${SESS}/func_filtered.${UID}.${NUM}.nii.gz ]; then
            3dTstat \
                -prefix ${SESS}/func_tmp_mean.${UID}.${NUM}.nii.gz \
                -mean ${SESS}/${INPUT}.${UID}.${NUM}.nii.gz
            
            3dTstat \
                -prefix ${SESS}/func_tmp_stdev.${UID}.${NUM}.nii.gz \
                -stdev ${SESS}/${INPUT}.${UID}.${NUM}.nii.gz
            
            # compute temporal SNR
            3dcalc \
                -a ${SESS}/func_tmp_mean.${UID}.${NUM}.nii.gz \
                -b ${SESS}/func_tmp_stdev.${UID}.${NUM}.nii.gz \
                -expr 'a/b' \
                -prefix ${SESS}/func_tSNR.${UID}.${NUM}.nii.gz
            
            # subtracts nuisances from inputs, retaining the mean
            3dcalc \
                -float \
                -a ${SESS}/${INPUT}.${UID}.${NUM}.nii.gz \
                -b ${SESS}/func_noise.${UID}.${NUM}.nii.gz \
                -c ${SESS}/func_tmp_mean.${UID}.${NUM}.nii.gz \
                -expr 'a-b+c' \
                -prefix ${SESS}/func_filtered.${UID}.${NUM}.nii.gz
        fi
    done
    rm ${SESS}/func_tmp_*
done
cd ${DIR_PIPE}

EOF
