#!/bin/bash

cat <<EOF
export INPUT=$(echo 'func_'${1})
export POLORT=$(echo ${2})
export GS_FLAG=$(echo ${3})
export VENT_FLAG=$(echo ${4})
export DV_FLAG=$(echo ${5})
export WM_LOC_FLAG=$(echo ${6})
export WM_GLO_FLAG=$(echo ${7})
export PC_FLAG=$(echo ${8})

EOF

cat <<"EOF"

echo '************************************************************************'
echo '                  Time series filtering of fMRI data'
echo ''
echo '   - Computes nusiance time series from tissues, motion paramaters,'
echo '   - Optionally uses the global mean: '${GS_FLAG}','
echo '   - Optionally uses the ventricles: '${VENT_FLAG}','
echo '   - Optionally uses the draining vessels: '${DV_FLAG}','
echo '   - Optionally uses the local white matter: '${WM_LOC_FLAG}','
echo '   - Optionally uses the mean white matter: '${WM_GLO_FLAG}','
echo '   - Detrends each with legrende polynomials up to order '${POLORT}','
echo '   - Computes fit of run with nusiances via least squares regression,'
echo '   - Computes temporal signal to noise ratio,'
echo '   - Subtracts noise model from each voxel, retaining the mean.'
echo ''
echo '************************************************************************'

cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # detrend physiological regressors, if they exist
        if [ -f ${SESS}/PARAMS/phys.${ID}.${NUM}.1D ] && \
           [ ! -f ${SESS}/PARAMS/det.phys.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/phys.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.phys.${ID}.${NUM}.1D
        fi

        # detrend motion regressors
        if [ ! -f ${SESS}/PARAMS/det.motion.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/motion.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.motion.${ID}.${NUM}.1D
        fi

        if [ ! -f ${SESS}/PARAMS/det.lag.motion.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.motion.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.motion.${ID}.${NUM}.1D
        fi
        
        # detrend ventricle regressors 
        if [ ! -f ${SESS}/PARAMS/det.vent.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/vent.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.vent.${ID}.${NUM}.1D
        fi
        
        if [ ! -f ${SESS}/PARAMS/det.lag.vent.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.vent.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.vent.${ID}.${NUM}.1D
        fi

        # detrend draining vessel regressors
        if [ ! -f ${SESS}/PARAMS/det.dv.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/dv.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.dv.${ID}.${NUM}.1D
        fi
        
        if [ ! -f ${SESS}/PARAMS/det.lag.dv.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.dv.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.dv.${ID}.${NUM}.1D
        fi
        
        # detrend local white matter regressors
        if [ ! -f ${SESS}/PARAMS/det.wm_local15.${ID}.${NUM}.nii.gz ]; then
            3dDetrend \
                -prefix ${SESS}/PARAMS/det.wm_local15.${ID}.${NUM}.nii.gz \
                -polort ${POLORT} \
                ${SESS}/PARAMS/wm_local15.${ID}.${NUM}.nii.gz
        fi

        if [ ! -f ${SESS}/PARAMS/det.lag.wm_local15.${ID}.${NUM}.nii.gz ]; then
            3dDetrend \
                -prefix ${SESS}/PARAMS/det.lag.wm_local15.${ID}.${NUM}.nii.gz \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.wm_local15.${ID}.${NUM}.nii.gz
        fi

        # detrend mean white matter regressors
        if [ ! -f ${SESS}/PARAMS/det.wm.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/wm.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.wm.${ID}.${NUM}.1D
        fi

        if [ ! -f ${SESS}/PARAMS/det.lag.wm.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.wm.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.wm.${ID}.${NUM}.1D
        fi

        # detrend global mean regressors
        if [ ! -f ${SESS}/PARAMS/det.global_mean.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/global_mean.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.global_mean.${ID}.${NUM}.1D
        fi

        if [ ! -f ${SESS}/PARAMS/det.lag.global_mean.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.global_mean.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.global_mean.${ID}.${NUM}.1D
        fi

        # detrend top pc regressors
        if [ ! -f ${SESS}/PARAMS/det.top_pc.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/top_pc.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.top_pc.${ID}.${NUM}.1D
        fi

        if [ ! -f ${SESS}/PARAMS/det.lag.top_pc.${ID}.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.top_pc.${ID}.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.top_pc.${ID}.${NUM}.1D
        fi
        
        # fit each run with all nuisance regressors
        if [ ! -f ${SESS}/func_noise.${ID}.${NUM}.nii.gz ]; then

            # start with the standard motion-parameter regressors
            CMD=`echo 3dTfitter \
                          -prefix ${SESS}/func_noise_betas.${ID}.${NUM}.nii.gz \
                          -fitts ${SESS}/func_noise.${ID}.${NUM}.nii.gz \
                          -polort ${POLORT} \
                          -RHS ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz \
                          -LHS ${SESS}/PARAMS/det.motion.${ID}.${NUM}.1D \
                               ${SESS}/PARAMS/det.lag.motion.${ID}.${NUM}.1D `

            # optionally add the global mean
            if [ `echo ${GS_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.global_mean.${ID}.${NUM}.1D`
            fi

            # optionally add the ventricles 
            if [ `echo ${VENT_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.vent.${ID}.${NUM}.1D`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.vent.${ID}.${NUM}.1D`
            fi

            # optionally add the draining vessles
            if [ `echo ${DV_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.dv.${ID}.${NUM}.1D`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.dv.${ID}.${NUM}.1D`
            fi

            # optionally add the local white matter regressors
            if [ `echo ${WM_LOC_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.wm_local15.${ID}.${NUM}.nii.gz`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.wm_local15.${ID}.${NUM}.nii.gz`
            fi
            
            # optionally add the global white matter regressors
            if [ `echo ${WM_GLO_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.wm.${ID}.${NUM}.1D`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.wm.${ID}.${NUM}.1D`
            fi

            if [ `echo ${PC_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.top_pc.${ID}.${NUM}.1D`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.top_pc.${ID}.${NUM}.1D`
            fi
            
            # and add the physio regressors if they exist
            if [ -f ${SESS}/PARAMS/det.phys.${ID}.${NUM}.1D ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.phys.${ID}.${NUM}.1D`
            fi

            ${CMD}

        fi

        # compute mean, standard deviation
        if [ ! -f ${SESS}/func_filtered.${ID}.${NUM}.nii.gz ]; then
            3dTstat \
                -prefix ${SESS}/func_tmp_mean.${ID}.${NUM}.nii.gz \
                -mean ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz
            
            3dTstat \
                -prefix ${SESS}/func_tmp_stdev.${ID}.${NUM}.nii.gz \
                -stdev ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz
            
            # compute temporal SNR
            3dcalc \
                -a ${SESS}/func_tmp_mean.${ID}.${NUM}.nii.gz \
                -b ${SESS}/func_tmp_stdev.${ID}.${NUM}.nii.gz \
                -expr 'a/b' \
                -prefix ${SESS}/func_tSNR.${ID}.${NUM}.nii.gz
            
            # subtracts nuisances from inputs, retaining the mean
            3dcalc \
                -float \
                -a ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz \
                -b ${SESS}/func_noise.${ID}.${NUM}.nii.gz \
                -c ${SESS}/func_tmp_mean.${ID}.${NUM}.nii.gz \
                -expr 'a-b+c' \
                -prefix ${SESS}/func_filtered.${ID}.${NUM}.nii.gz
        fi
    done
    rm ${SESS}/func_tmp_*
done
cd ${DIR_PIPE}

EOF
