#!/bin/bash

cat <<EOF
INPUT=`echo 'func_'${1}`
POLORT=`echo ${2}`
GS_FLAG=`echo ${3}`
VENT_FLAG=`echo ${4}`
DV_FLAG=`echo ${5}`
WM_FLAG=`echo ${6}`

echo '************************************************************************'
echo '                  Time series filtering of fMRI data'
echo ''
echo '   - Computes nusiance time series from tissues, motion paramaters,'
echo '   - Optionally uses the global mean: ' ${GS_FLAG} ','
echo '   - Optionally uses the ventricles: ' ${VENT_FLAG} ','
echo '   - Optionally uses the draining vessels: ' ${DV_FLAG} ','
echo '   - Optionally uses the local white matter: ' ${WM_FLAG} ','
echo '   - Detrends each with legrende polynomials up to order ' ${POLORT}','
echo '   - Computes fit of run with all nusiances via linear regression,'
echo '   - Computes temporal signal to noise ratio,'
echo '   - Subtracts noise model from each voxel, retaining the mean.'
echo ''
echo '************************************************************************'

EOF

cat <<"EOF"
cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # detrend physiological regressors, if they exist
        if [ -f ${SESS}/PARAMS/phys.${NUM}.1D ] && \
           [ ! -f ${SESS}/PARAMS/det.phys.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/phys.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.phys.${NUM}.1D
        fi

        # detrend motion regressors
        if [ ! -f ${SESS}/PARAMS/det.motion.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/motion.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.motion.${NUM}.1D
        fi

        if [ ! -f ${SESS}/PARAMS/det.lag.motion.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.motion.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.motion.${NUM}.1D
        fi
        
        # detrend ventricle regressors 
        if [ ! -f ${SESS}/PARAMS/det.vent.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/vent.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.vent.${NUM}.1D
        fi
        
        if [ ! -f ${SESS}/PARAMS/det.lag.vent.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.vent.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.vent.${NUM}.1D
        fi

        # detrend draining vessel regressors
        if [ ! -f ${SESS}/PARAMS/det.dv.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/dv.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.dv.${NUM}.1D
        fi
        
        if [ ! -f ${SESS}/PARAMS/det.lag.dv.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.dv.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.lag.dv.${NUM}.1D
        fi
        
        # detrend local white matter regressors
        if [ ! -f ${SESS}/PARAMS/det.wm_local15.${NUM}.nii.gz ]; then
            3dDetrend \
                -prefix ${SESS}/PARAMS/det.wm_local15.${NUM}.nii.gz \
                -polort ${POLORT} \
                ${SESS}/PARAMS/wm_local15.${NUM}.nii.gz
        fi

        if [ ! -f ${SESS}/PARAMS/det.lag.wm_local15.${NUM}.nii.gz ]; then
            3dDetrend \
                -prefix ${SESS}/PARAMS/det.lag.wm_local15.${NUM}.nii.gz \
                -polort ${POLORT} \
                ${SESS}/PARAMS/lag.wm_local15.${NUM}.nii.gz
        fi

        # detrend global mean regressors
        if [ ! -f ${SESS}/PARAMS/det.global_mean.${NUM}.1D ]; then
            3dDetrend \
                -prefix - \
                -DAFNI_1D_TRANOUT=YES \
                -polort ${POLORT} \
                ${SESS}/PARAMS/global_mean.${NUM}.1D\' > \
                ${SESS}/PARAMS/det.global_mean.${NUM}.1D
        fi
        
        # fit each run with all nuisance regressors
        if [ ! -f ${SESS}/func_noise.${NUM}.nii.gz ]; then

            # start with the standard motion-parameter regressors
            CMD=`echo 3dTfitter \
                          -prefix ${SESS}/func_noise_betas.${NUM}.nii.gz \
                          -fitts ${SESS}/func_noise.${NUM}.nii.gz \
                          -polort ${POLORT} \
                          -RHS ${SESS}/${INPUT}.${NUM}.nii.gz \
                          -LHS ${SESS}/PARAMS/det.motion.${NUM}.1D \
                               ${SESS}/PARAMS/det.lag.motion.${NUM}.1D `

            # optionally add the global mean
            if [ `echo ${GS_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.global_mean.${NUM}.1D`
            fi

            # optionally add the ventricles 
            if [ `echo ${VENT_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.vent.${NUM}.1D`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.vent.${NUM}.1D`
            fi

            # optionally add the draining vessles
            if [ `echo ${DV_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.dv.${NUM}.1D`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.dv.${NUM}.1D`
            fi

            # optionally add the local white matter regressors
            if [ `echo ${WM_FLAG}` = 'on' ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.wm_local15.${NUM}.nii.gz`
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.lag.wm_local15.${NUM}.nii.gz`
            fi

            # and add the physio regressors if they exist
            if [ -f ${SESS}/PARAMS/det.phys.${NUM}.1D ]; then
                CMD=`echo ${CMD} ${SESS}/PARAMS/det.phys.${NUM}.1D`
            fi

            ${CMD}

        fi

        # compute mean, standard deviation
        if [ ! -f ${SESS}/func_filtered.${NUM}.nii.gz ]; then
            3dTstat \
                -prefix ${SESS}/func_tmp_mean.${NUM}.nii.gz \
                -mean ${SESS}/${INPUT}.${NUM}.nii.gz
            
            3dTstat \
                -prefix ${SESS}/func_tmp_stdev.${NUM}.nii.gz \
                -stdev ${SESS}/${INPUT}.${NUM}.nii.gz
            
            # compute temporal SNR
            3dcalc \
                -a ${SESS}/func_tmp_mean.${NUM}.nii.gz \
                -b ${SESS}/func_tmp_stdev.${NUM}.nii.gz \
                -expr 'a/b' \
                -prefix ${SESS}/func_tSNR.${NUM}.nii.gz
            
            # subtracts nuisances from inputs, retaining the mean
            3dcalc \
                -float \
                -a ${SESS}/${INPUT}.${NUM}.nii.gz \
                -b ${SESS}/func_noise.${NUM}.nii.gz \
                -c ${SESS}/func_tmp_mean.${NUM}.nii.gz \
                -expr 'a-b+c' \
                -prefix ${SESS}/func_filtered.${NUM}.nii.gz
        fi
    done
    rm ${SESS}/func_tmp_*
done
cd ${DIR_PIPE}

EOF
