#!/bin/bash

cat <<EOF
export INPUT=`echo 'func_'${1}`
export TRAINDATA=`echo ${2}`
export THRESHOLD=`echo ${3}`

EOF

cat <<"EOF"

echo '************************************************************************'
echo '                MELODIC-based component regression using FIX'
echo ''
echo '                                 LOL :D                                 '
echo ''
echo '   - Runs FSL fix on MELODIC outputs using '${TRAINDATA}'.'
echo ''
echo '************************************************************************'

cd /tmp

# find the FSL FIX folder
DIR_FIX=`which fix`
DIR_FIX=`dirname ${DIR_FIX}`

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # run FIX X-noisifier -- no highpass options for now...
        if [ ! -f ${SESS}/func_fix.${ID}.${NUM}.nii.gz ]; then
            
            ## create a fake FEAT directory
            mkdir ${SESS}/fake.${ID}.${NUM}.feat
            mkdir ${SESS}/fake.${ID}.${NUM}.feat/reg
            mkdir ${SESS}/fake.${ID}.${NUM}.feat/mc

            ## copy relevent nifti inputs
            # melodic (command-line program) full output 
            cp -r \
                ${SESS}/MELODIC.${ID}.${NUM} \
                ${SESS}/fake.${ID}.${NUM}.feat/filtered_func_data.ica

            # preprocessed 4D data
            cp \
                ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz \
                ${SESS}/fake.${ID}.${NUM}.feat/filtered_func_data.nii.gz

            # raw data (for generating motion paramaters)
            cp \
                ${SESS}/func_ob.${ID}.${NUM}.nii.gz \
                ${SESS}/fake.${ID}.${NUM}.feat/mc/prefiltered_func_data.nii.gz

            # temporal mean of 4D data
            cp ${SESS}/anat_EPI_brain.nii.gz ${SESS}/fake.${ID}.${NUM}.feat/mean_func.nii.gz
            
            # valid mask relating to the 4D data
            cp ${SESS}/anat_EPI_mask.nii.gz ${SESS}/fake.${ID}.${NUM}.feat/mask.nii.gz

            ## generate FSL-friendly motion paramaters
            mcflirt \
                -in ${SESS}/fake.${ID}.${NUM}.feat/mc/prefiltered_func_data.nii.gz \
                -stats \
                -mats \
                -plots \
                -report 
            
            ## fill in registration folder
            # example image from 4D data
            cp \
                ${SESS}/anat_EPI_brain.nii.gz \
                ${SESS}/fake.${ID}.${NUM}.feat/reg/example_func.nii.gz
            
            # brain-extracted structural
            cp \
                ${SESS}/anat_T1_brain.nii.gz \
                ${SESS}/fake.${ID}.${NUM}.feat/reg/highres.nii.gz

            # FLIRT transform from structural to functional space
            cp \
                ${SESS}/mat_T1_to_EPI.mat \
                ${SESS}/fake.${ID}.${NUM}.feat/reg/highres2example_func.mat

            # 3dcopy \
            #     ${DIR_AFNI}/MNI_avg152T1+tlrc \
            #     ${SESS}/MELODIC.${ID}.${NUM}/reg/standard.nii.gz
            # cp \
            #     ${SESS}/mat_TAL_to_EPI.mat \
            #     ${SESS}/MELODIC.${ID}.${NUM}/reg/standard2example_func.mat
            # cp \
            #     ${SESS}/mat_EPI_to_TAL.mat \
            #     ${SESS}/MELODIC.${ID}.${NUM}/reg/example_func2standard.mat

            # FSL FIXAFY TILL THE BREAK OF DAWN 
            # https://www.youtube.com/watch?v=uu6DRAvHJVM
            fix \
                ${SESS}/fake.${ID}.${NUM}.feat \
                ${DIR_FIX}/training_data/${TRAINDATA} \
                ${THRESHOLD}

            # copy output to SESS folder
            mv \
                ${SESS}/fake.${ID}.${NUM}.feat/filtered_func_data_clean.nii.gz \
                ${SESS}/func_fix.${ID}.${NUM}.nii.gz

            # X-destroyifiy fake.feat
            rm -r ${SESS}/fake.${ID}.${NUM}.feat
        fi 
    done
done

EOF