#!/bin/bash

cat <<EOF
INPUT=`echo 'func_'${1}`
DIMS=`echo ${2}`

echo '************************************************************************'
echo '                       AFNI T1-transform data'
echo ''
echo '   - Resamples ${INPUT} data to T1 space at ${DIMS}^3mm,'
echo '   - Transforms whole-brain masks to T1 space.'
echo ''
echo '************************************************************************'

EOF

cat <<"EOF"
cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # register runs with T1
        if [ ! -f ${SESS}/func_MNI.${NUM}.nii.gz ]; then
            3dAllineate \
                -prefix ${SESS}/func_T1.${NUM}.nii.gz \
                -input ${SESS}/${INPUT}.${NUM}.nii.gz \
                -1Dmatrix_apply ${SESS}/mat_EPI_to_T1.aff12.1D \
                -master ${SESS}/reg_EPI_to_T1.nii.gz \
                -float \
                -final wsinc5 \
                -mast_dxyz ${DIMS} ${DIMS} ${DIMS}
        fi
    done

    # register session masks with T1
    if [ ! -f ${SESS}/anat_EPI_mask_MNI.nii.gz ]; then
        3dAllineate \
            -prefix ${SESS}/anat_EPI_mask_T1.nii.gz \
            -input ${SESS}/anat_EPI_mask.nii.gz \
            -1Dmatrix_apply ${SESS}/mat_EPI_to_T1.aff12.1D \
            -master ${SESS}/reg_EPI_to_T1.nii.gz \
            -float \
            -final NN \
            -mast_dxyz ${DIMS} ${DIMS} ${DIMS}
    fi
done

cd ${DIR_PIPE}

EOF
