#!/bin/bash

cat <<EOF
INPUT=`echo 'func_'${1}`
MASK=`echo 'anat_'${2}`
FILTER=`echo ${3}`
CUTOFF=`echo ${4}`

echo '************************************************************************'
echo '                          Low-Pass Module'
echo ''
echo '   - Low-passes masked functional data using a ${FILTER} filter.'
echo ''
echo '************************************************************************'

EOF

cat <<"EOF"
cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        if [ ! -f ${SESS}/func_lowpass.${NUM}.nii.gz ]; then
            
            # set input paths
            FUNC=`echo ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz`
            ANAT=`echo ${SESS}/${MASK}.nii.gz`

            # lowpass data
            python ${DIR_PIPE}/epitome/lowpass.py \
                ${FUNC} \
                ${INPUT} \
                ${ANAT} \
                ${CUTOFF} \
                ${SESS} \
                ${ID} \
                ${NUM}
        fi
    done
done

cd ${DIR_PIPE}

EOF
