#!/bin/bash

cat <<"EOF"

echo '************************************************************************'
echo '             AFNI: NonLinear registration pathway calculator'
echo ''
echo '   Calculates MNI152 warp from the linreg outputs'
echo '   - Requires a successful run of linreg_calc to work properly!'
echo ''
echo '************************************************************************'

cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    SESS=`basename ${SESS}`
    DIR=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}`
    DIR_T1=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/T1`

    # retrieve the MNI target brain
    3dcopy \
        ${DIR_AFNI}/MNI_avg152T1+tlrc template

    # calculate the nonlinear warp between the reg_T1_to_TAL and the MNI brain.
    if [ ! -f ${DIR_T1}/anat_T1_nlinreg_WARP.nii.gz ]; then
        3dQwarp \
            -prefix ${DIR}/reg_nlin_TAL \
            -blur 0 -3 \
            -iwarp \
            -resample \
            -base template \
            -source ${DIR}/reg_T1_to_TAL.nii.gz
    fi

done

EOF
