#!/bin/bash

cat <<EOF
export INPUT=`echo 'func_${1}'`
export DIMS=`echo ${2}`

EOF

cat <<"EOF"

echo '************************************************************************'
echo '                       FSL MNI-transform data'
echo ''
echo '   - Resamples '${INPUT}' data to MNI space at '${DIMS}'^3mm,'
echo '   - Transforms whole-brain masks to MNI space,'
echo '   - Creates 1 concatenated run per participant in run order.'
echo ''
echo '             DO NOT RUN LINREG_EPI2MNI_FSL BEFORE THIS!!!'
echo '                    This does that part for you :)'
echo ''
echo '************************************************************************'

cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in `basename ${DIR_SESS}`; do
    
    DIR=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/${SESS}`
    DIR_T1=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/T1/${SESS}`

    # create registration dummy for FSL
    3dresample -dxyz ${DIMS} ${DIMS} ${DIMS} \
               -prefix ${DIR}/anat_EPI_reg_target.nii.gz \
               -inset ${DIR_T1}/anat_T1_brain.nii.gz

    DIR_RUNS=`ls -d -- ${DIR}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # register runs with MNI
        if [ ! -f ${DIR}/func_MNI-nonlin.${ID}.${NUM}.nii.gz ]; then
            applywarp \
                --ref=${DIR_DATA}/${DIR_EXPT}/anat_MNI.nii.gz \
                --in=${SESS}/${INPUT}.${ID}.${NUM}.nii.gz \
                --aff=${SESS}/mat_EPI_to_TAL.mat \
                --warp=${SESS}/reg_nlin_TAL_WARP.nii.gz \
                --premat=${SESS}/mat_EPI_to_TAL.mat \
                --out=${SESS}/func_MNI-nonlin.${ID}.${NUM}.nii.gz
        fi
    done
    
    # register session masks with MNI
    if [ ! -f ${SESS}/anat_EPI_mask_MNI-nonlin.nii.gz ]; then
            applywarp \
                --ref=${DIR_DATA}/${DIR_EXPT}/anat_MNI.nii.gz
                --in=${SESS}/anat_EPI_mask.nii.gz
                --aff=${SESS}/mat_EPI_to_TAL.mat \
                --warp=${SESS}/reg_nlin_TAL_WARP.nii.gz \
                --premat=${SESS}/mat_EPI_to_TAL.mat \
                --out=${SESS}/anat_EPI_mask_MNI-nonlin.nii.gz
    fi
done

cd ${DIR_PIPE}

EOF
