#!/bin/bash

cat <<EOF
export INPUT=`echo 'func_'${1}`
export DIMS=`echo ${2}`

EOF

cat <<"EOF"

echo '************************************************************************'
echo '                  Nonlinear: AFNI MNI-transform data'
echo ''
echo '   - Resamples '${INPUT}' data to MNI space at '${DIMS}'^3mm,'
echo '   - Transforms whole-brain masks to MNI space,'
echo ''
echo '************************************************************************'


cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # register runs with MNI
        if [ ! -f ${SESS}/func_MNI.${ID}.${NUM}.nii.gz ]; then
            3dNwarpApply \
                -prefix ${SESS}/func_MNI.${ID}.${NUM}.nii.gz \
                -source ${SEES}/${INPUT}.${ID}.${NUM}.nii.gz \
                -affter ${SESS}/mat_EPI_to_TAL.aff12.1D \
                -dxyz ${DIMS} \
                -nwarp ${SESS}/reg_nlin_TAL_WARP.nii.gz
        fi
    done
    
    # register session masks with MNI
    if [ ! -f ${SESS}/anat_EPI_mask_MNI.nii.gz ]; then
        3dwarpApply \
            -prefix ${SESS}/anat_EPI_mask_MNI.nii.gz \
            -source ${SESS}/anat_EPI_mask.nii.gz \
            -affter ${SESS}/mat_EPI_to_TAL.aff12.1D \
            -dxyz ${DIMS} \
            -ainterp NN \
            -nwarp ${SESS}/reg_nlin_TAL_WARP.nii.gz
    fi
done

cd ${DIR_PIPE}

EOF
