#!/bin/bash

# set variables
INPUT=`echo 'func_'${1}`
MASK=`echo 'anat_${2}'`

## calculate global correlation for each concatenated run
cd /tmp
for SUB in ${SUBJECTS}; do
    for SESS in `ls -d ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`; do
        for FILE in `ls ${SESS}/${INPUT}.*.nii.gz`; do
            FNAME=`basename ${FILE}`
            if [ ! -f ${SESS}/${PARAMS}/${FNAME}.gcorr ]; then
                @compute_gcor \
                    -input ${FILE} \
                    -verb 0 \
                    -mask ${SESS}/anat_${2}.nii.gz \
                    > ${SESS}/${PARAMS}/${FNAME}.gcorr
            fi
        done # file
    done # session
done # subject
cd ${DIR_PIPE}
