#!/bin/bash

## Standard Space Module: Prepares data for analysis in standard space

INPUT=`echo 'func_${1}'`
MASK=`echo 'anat_${2}'`

cd /tmp
for SUB in ${SUBJECTS}; do
    DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
    for SESS in ${DIR_SESS}; do
        DIR_RUNS=`ls -d -- ${SESS}/RUN*`
        for RUN in ${DIR_RUNS}; do
            NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

            # smooth data within mask
            if [ ! -f ${SESS}/func_smooth.${NUM}.nii.gz ]; then
                3dBlurInMask \
                    -prefix ${SESS}/func_smooth.${NUM}.nii.gz \
                    -FWHM ${BLUR_FWHM} \
                    -mask ${SESS}/${MASK}.nii.gz \
                    -input ${SESS}/${INPUT}.${NUM}.nii.gz
            fi

            # register runs with MNI
            if [ ! -f ${SESS}/func_MNI.${NUM}.nii.gz ]; then
                3dAllineate \
                    -prefix ${SESS}/func_MNI.${NUM}.nii.gz \
                    -input ${SESS}/func_smooth.${NUM}.nii.gz \
                    -1Dmatrix_apply ${SESS}/mat_EPI_to_TAL.aff12.1D \
                    -master ${DIR_AFNI}/MNI_avg152T1+tlrc \
                    -float \
                    -final wsinc5 \
                    -mast_dxyz ${DIMS} ${DIMS} ${DIMS}
            fi
        done
        
        # register session masks with MNI
        if [ ! -f ${SESS}/anat_EPI_mask_MNI.nii.gz ]; then
            3dAllineate \
                -prefix ${SESS}/anat_EPI_mask_MNI.nii.gz \
                -input ${SESS}/anat_EPI_mask.nii.gz \
                -1Dmatrix_apply ${SESS}/mat_EPI_to_TAL.aff12.1D \
                -master ${DIR_AFNI}/MNI_avg152T1+tlrc \
                -float \
                -final NN \
                -mast_dxyz ${DIMS} ${DIMS} ${DIMS}
        fi
    done
    
    # create concatenated runs in order
    if [ ! -f ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/func_concat.nii.gz ]; then
        LIST=``
        DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
        for SESS in ${DIR_SESS}; do
            FILES=`ls ${SESS}/func_MNI*`
            LIST="${LIST} ${FILES}"
        done    
        
        3dTcat \
            -prefix ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/func_concat.nii.gz \
            `echo ${LIST}` 
    fi
done

# create experiment wide mask
if [ ! -f ${DIR_DATA}/${DIR_EXPT}/mask_group.nii.gz ]; then
    3dmask_tool \
        -input ${DIR_DATA}/${DIR_EXPT}/*/${DATA_TYPE}/*/anat_EPI_mask_MNI.nii.gz \
        -prefix ${DIR_DATA}/${DIR_EXPT}/mask_group_MNI.nii.gz -frac 1.0
fi
cd ${DIR_PIPE}

