#!/bin/bash
#
# vol2hcp input fwhm
#
# input: input prefix
# fwhm: surface smoothing kernel full width half max [float]
# output: func_surface
# prereq: fsrecon
#
# Projects functional data from native volume space to human connectome project space.

echo '*** MODULE: vol2hcp. Projects functional data onto HCP space. *'
export input=${1}
export fwhm=${2}

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    SESS=`basename ${SESS}`
    DIR=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/${SESS}`
    DIR_T1=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/T1/${SESS}`
    DIR_FS=`echo ${SUBJECTS_DIR}/${DIR_EXPT}_${SUB}_${SESS}`
    FS_NAME=`echo ${DIR_EXPT}_${SUB}_${SESS}`

done
